### ISSUE TITLE
LiveLeak changed to ItemFix

### ISSUE THREAD

**Issue by napgiver** [Botster/plugin.video.liveleak#10]
Please update to reflect the websites change from _www.liveleak.com_ to _www.itemfix.com_

**Comment by Botster** [comment]
I'm sorry, but, It is not just a simple update. The Liveleak plugin is dead and should be removed from the available plugins.

Please see:
https://github.com/Botster/plugin.video.liveleak/issues/9#issuecomment-834829146

and:
https://forum.kodi.tv/showthread.php?tid=135821&pid=3035205#pid3035205
