### ISSUE TITLE
Only yoursay and entertainment groups are returning results

### ISSUE THREAD

**Issue by vecnar** [Botster/plugin.video.liveleak#2]
Hello,
I am not sure if i am correct  placing issue here so please advise where to move the post if not appropriate.

I have been using liveleak addon for a few years and only today started having problems opening "featured" group/folder. I tested all groups and only "yoursay" and "entertainment" return results, search doesn't return anything as well.

Kodi version: Kodi (18.4 Git:20190831-3ade758ceb). Platform: Windows NT x86 64-bit
liveleak addon version: plugin.video.liveleak v1.3.5

Below is the error i found in the kodi.log
`2020-05-30 23:12:09.529 T:5712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 388, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 279, in index
                                                items = pool.map(fetchItemDetails, posts)
                                              File "C:\Program Files\Kodi\system\python\Lib\multiprocessing\pool.py", line 251, in map
                                                return self.map_async(func, iterable, chunksize).get()
                                              File "C:\Program Files\Kodi\system\python\Lib\multiprocessing\pool.py", line 567, in get
                                                raise self._value
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--`

Thank you

Oleg

**Comment by Botster** [comment]
Yes, reporting it here is fine. You could also have reported it in the LiveLeak thread on the Kodi forum: https://forum.kodi.tv/showthread.php?tid=135821

I experienced the same type of issue as well this evening. The error text you provided helped me confirm my suspicion regarding the problem. Thank you.

I have uploaded a quick fix, but I need to add in some error trapping at that very point before I issue a pull request to the Kodi repository.

If you want to download the quick-fix version now, go to the Code tab, click Clone or download, then Download ZIP. Unzip it in your kodi folder (I don't know what that is on Windows), and rename it to remove "-master".

**Comment by vecnar** [comment]
Thank you for a quick response and release of quick fix!
I read your post on the kodi forum, i will check the forum from time to time.

In case it helps anyone using windows below are the steps i used, not sure if they are correct but it worked for me:

1. Close kodi
2. Open windows explorer
3. In address bar paste below line (except 4. at the start) and hit enter
4. %appdata%\kodi\addons
5. Move existing liveleak folder elsewhere for backup purposes, cut and paste
6. Extract "plugin.video.liveleak-master" from zip file, rename to "plugin.video.liveleak" and place in "%appdata%\kodi\addons"


Thank you

Oleg

**Comment by vecnar** [comment]
Hello,

I am not able to open liveleak today after previous update, i think the error is slightly different and i thought to post here in case that helps.

`-01 23:31:59.371 T:9292   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 413, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 290, in index
                                                meta['rating'] = item.find('samp', class_='thing_score').get_text()
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--`

**Comment by Botster** [comment]
Thank you for providing that relevant error text. It told me exactly where to look.

Unfortunately, the site's page code I looked at still has the element the plugin is looking for. It could have been just a transient bug in their HTML code. Could you try again please?

**Comment by vecnar** [comment]
Good morning,

I tried on multiple devices but i get error with liveleak version 1.4.0. I tried last night and now as well. This time none of the groups are opening, i didn't check yesterday but did today.

`2020-06-02 10:48:52.871 T:9940   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 458, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 335, in index
                                                meta['rating'] = item.find('samp', class_='thing_score').get_text()
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--
2020-06-02 10:48:52.913 T:960   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26in_bookmark_folder_id%3d1%26page%3d1
2020-06-02 10:48:52.922 T:2976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26in_bookmark_folder_id%3d1%26page%3d1) failed`

**Comment by Botster** [comment]
Thank you for that apt error message. I am sorry it is not working for you.

I just re-examined the LL HTML code and tested the plugin on two different machines using two different Kodi versions and experienced no problems. So, I currently have no clue why it throws an error on your devices.

To hopefully get you up and running, though, and if you're comfortable doing so, please edit default.py in your "%appdata%\kodi\addons\plugin.video.liveleak" folder. Go to line 335 and change it from:
        meta['rating'] = item.find('samp', class_='thing_score').get_text()
to:
        #meta['rating'] = item.find('samp', class_='thing_score').get_text()
        meta['rating'] = '?'

What you are doing is commenting out the existing line and adding the new line below it. Be sure to maintain the indentation of 8 _spaces_ (not 2 tabs).

**Comment by vecnar** [comment]
Thank you for trying to identify where the problem might be.
I modified default.py as per your instructions and below is the error from the log. Let me know if you would like me to try something else.

`2020-06-02 22:16:18.284 T:9324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 459, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 338, in index
                                                meta['credit'] = item.find('div', class_='featured_text_con').a.get_text()
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--
2020-06-02 22:16:18.333 T:8856   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26in_bookmark_folder_id%3d1%26page%3d1
2020-06-02 22:16:18.345 T:2588   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26in_bookmark_folder_id%3d1%26page%3d1) failed
`

**Comment by Botster** [comment]
Thank you for trying. It seems as though the Liveleak page is not being fetched completely or properly. There is a 15 second timeout for a page load. It you have to wait 15 seconds and then you get an error, this might be the reason.

At any rate, I've added in some exception tolerance to hopefully get us past those errors. You just won't get the Liveleak users' rating and/or the username of the person that posted the video.

I've attached a ZIP of default.py. Download it and, after making a backup of the existing file, copy it into the appropriate folder. And, let's see if this works for you.

[default.zip](https://github.com/Botster/plugin.video.liveleak/files/4720188/default.zip)

(If you have trouble downloading it, let me know and I'll push it to the repository so you can get it there.)

**Comment by vecnar** [comment]
Thank you for doing that. I am based in Ireland on virgin media internet connection so maybe it has something to do with that. Usernames and ratings are not important.
I tried featured, wtf and search and they worked, i mainly use featured to see the videos. I checked the log and no errors from liveleak plugin.

**Comment by Botster** [comment]
Good, I'm glad it's working for you. Be advised, the Label User feature will not work as it should if there are duplicate 'Unknown User's.

I'm going to leave this issue open for a day or three longer. If you can, will you please report back to me if a lot of the Usernames and Ratings are 'Unknown' or '?'. I'd like to see if I might need to figure out how to make the plugin even more fault tolerant.

**Comment by vecnar** [comment]
Thank you for your work and trying to make it better.
I am not sure if i am checking correctly as i haven't used info button on each video previously. I went through 2 pages of videos under "featured" and for all "writer" is "Unknown User", Rated is different for most videos "GA" and "PG" and i couldn't find any with "unknown" or "?", so it looks like the usernames/writer is the only problem.
Let me know if i can assist you with anything.

**Comment by Botster** [comment]
That info helps very much. Thank you.
I'm closing this ticket now. Please do let me know it you experience any other issues.

**Comment by vecnar** [comment]
Will do, thank you.
