### ISSUE TITLE
Failed to install due to a invalid structure.

### ISSUE THREAD

**Issue by john12345670** [Botster/plugin.video.liveleak#8]
Hello Botster, I went to the (Jarvis, Krypton, Leia) branch, then I clicked on the  green code button and selected "download zip", I put the "plugin.video.liveleak-jarvis.zip" on a USB stick and tried to install it on my Kodi v18.7 (Leia) box and it just says failed to install due to a invalid structure.

Can you look into it? Thanks.

**Comment by Botster** [comment]
Okay, I figured out that Kodi is very strict when parsing XML files. I have uploaded a fresh file.

Please try again.

**Comment by john12345670** [comment]
Thank you Botster! I can now install the plugin, but I think the fanart jpg is in the wrong folder so I don't have the Liveleak thumbnail icon showing up. 

One more thing I would like to report, is the check mark that shows which videos has been watched previously doesn't work right. Some videos will have the check mark showing you've viewed it already, but most don't and after a reboot of the system the check marked videos will revert back to no mark. This is not essential to the working of the plugin, but would be nice to have it working again. 

Anyway thank you for maintaining the plugin, it's very much appreciated!

**Comment by Botster** [comment]
You're welcome.

Hmm, I get the fanart background and the thumbnail icon on my system. According to the Add-on Development documentation, except for Kodi v16, those files can be anywhere in the addon directory. Anyway, I moved them to the top-level directory and pushed an update in case you want to have those graphics showing up like they should.

About the previously watched videos tracking, as far as I recall, that never worked properly. The original version had no tracking of that, and I did not add any tracking preferring to rely on Kodi itself for that. And, yes, after a reboot or relaunch, it forgets. I may look into seeing if I can add that, but with summer being here, my free time is short.

**Comment by john12345670** [comment]
Thank you for updating the thumbnail location, it's now showing the liveleak icon like before. 

It's weird that the documentation says the icon picture can go anywhere, but it doesn't work for my version of Kodi. It's a perplexing situation I find myself in, maybe this is the kick in the pants for me to redo my Kodi build and upgrade to Kodi v19. I don't know.

The video tracking feature was working before, but now that you mention Kodi was doing that side of things instead of the plugin. It makes sense because I think it was working on v14 of Kodi, and they must have changed something that breaks the tracking on later versions. Like I said before, it's a nice feature to have but not essential for the plugin so have a look into it when you have some free time.

Thank you and I hope you enjoy the summer, all the best.

**Comment by Botster** [comment]
> maybe this is the kick in the pants for me to redo my Kodi build and upgrade to Kodi v19. I don't know.

Just FYI, the performance of the Liveleak plugin on Kodi 19 is terrible.

The plugin has to do many web page fetches merely to populate just one page of videos. The multiprocessing module I rely on to speed this up is unavailable due to a bug in the build which I reported but has yet to be addressed. And, to make things worse, to accommodate favored skins, Kodi core forces a container refresh after _every_ media play causing the entire process of fetching all those web pages to be repeated yet again.

The only reason I have Kodi 19 on one of my machines is so I could test the version for Matrix. I have frozen the version on my daily driver at 18.9. It will not be updated.

**Comment by Botster** [comment]
Thank you for the info on BeautifulSoup4. I hadn't noticed an issue so that's very helpful.

Do you mind if I go ahead and close this issue?

**Comment by john12345670** [comment]
Yes. Please close the issue. It's been addressed. Thank you Botster.

**Comment by Botster** [comment]
You're welcome! :-)
